#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetResfulService.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="mngpets")]
	public partial class PetSerDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPetSer(PetSer instance);
    partial void UpdatePetSer(PetSer instance);
    partial void DeletePetSer(PetSer instance);
    #endregion
		
		public PetSerDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["mngpetsConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PetSerDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PetSerDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PetSerDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PetSerDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PetSer> PetSers
		{
			get
			{
				return this.GetTable<PetSer>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PetSer")]
	public partial class PetSer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _CusName;
		
		private string _PetName;
		
		private System.Nullable<char> _PetGender;
		
		private string _PetAge;
		
		private System.Nullable<double> _PetWeight;
		
		private string _PetType;
		
		private string _WhatServices;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCusNameChanging(string value);
    partial void OnCusNameChanged();
    partial void OnPetNameChanging(string value);
    partial void OnPetNameChanged();
    partial void OnPetGenderChanging(System.Nullable<char> value);
    partial void OnPetGenderChanged();
    partial void OnPetAgeChanging(string value);
    partial void OnPetAgeChanged();
    partial void OnPetWeightChanging(System.Nullable<double> value);
    partial void OnPetWeightChanged();
    partial void OnPetTypeChanging(string value);
    partial void OnPetTypeChanged();
    partial void OnWhatServicesChanging(string value);
    partial void OnWhatServicesChanged();
    #endregion
		
		public PetSer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CusName", DbType="NChar(15)")]
		public string CusName
		{
			get
			{
				return this._CusName;
			}
			set
			{
				if ((this._CusName != value))
				{
					this.OnCusNameChanging(value);
					this.SendPropertyChanging();
					this._CusName = value;
					this.SendPropertyChanged("CusName");
					this.OnCusNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PetName", DbType="NChar(10)")]
		public string PetName
		{
			get
			{
				return this._PetName;
			}
			set
			{
				if ((this._PetName != value))
				{
					this.OnPetNameChanging(value);
					this.SendPropertyChanging();
					this._PetName = value;
					this.SendPropertyChanged("PetName");
					this.OnPetNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PetGender", DbType="NChar(1)")]
		public System.Nullable<char> PetGender
		{
			get
			{
				return this._PetGender;
			}
			set
			{
				if ((this._PetGender != value))
				{
					this.OnPetGenderChanging(value);
					this.SendPropertyChanging();
					this._PetGender = value;
					this.SendPropertyChanged("PetGender");
					this.OnPetGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PetAge", DbType="NChar(10)")]
		public string PetAge
		{
			get
			{
				return this._PetAge;
			}
			set
			{
				if ((this._PetAge != value))
				{
					this.OnPetAgeChanging(value);
					this.SendPropertyChanging();
					this._PetAge = value;
					this.SendPropertyChanged("PetAge");
					this.OnPetAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PetWeight", DbType="Float")]
		public System.Nullable<double> PetWeight
		{
			get
			{
				return this._PetWeight;
			}
			set
			{
				if ((this._PetWeight != value))
				{
					this.OnPetWeightChanging(value);
					this.SendPropertyChanging();
					this._PetWeight = value;
					this.SendPropertyChanged("PetWeight");
					this.OnPetWeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PetType", DbType="NChar(10)")]
		public string PetType
		{
			get
			{
				return this._PetType;
			}
			set
			{
				if ((this._PetType != value))
				{
					this.OnPetTypeChanging(value);
					this.SendPropertyChanging();
					this._PetType = value;
					this.SendPropertyChanged("PetType");
					this.OnPetTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WhatServices", DbType="NChar(50)")]
		public string WhatServices
		{
			get
			{
				return this._WhatServices;
			}
			set
			{
				if ((this._WhatServices != value))
				{
					this.OnWhatServicesChanging(value);
					this.SendPropertyChanging();
					this._WhatServices = value;
					this.SendPropertyChanged("WhatServices");
					this.OnWhatServicesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
